apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: speedtest-app
  name: speedtest-app
  namespace: speedtest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: speedtest-app
  template:
    metadata:
      labels:
        app: speedtest-app
    spec:
      containers:
      - name: speedtest-app
        image: registry.tino.sh/speedtest
        envFrom:
          - configMapRef:
              name: speedtest-conf
        resources:
          requests:
            memory: "30Mi"
            cpu: "30m"
          limits:
            memory: "64Mi"
            cpu: "200m"
        ports:
        - containerPort: 80
